### PR TITLE
Support Watch Only Accounts

### PR DESCRIPTION
**Pull request by icyblob**
Support watch only accounts:
- Add watch only accounts
- Export vault file with watch only accounts and able to import it on web wallet
- Import vault file with watch only accounts
Support multi-languages

Will support verifyIdentity later.
@sallymoc @Qubic-Hub

### CODE REVIEW

**Comment by Qubic-Hub** [comment]
@icyblob please rebase from develop so that conflicts in l10n are not conflicted

**Comment by sallymoc** [comment]
Please also include the option to scan a QR with the address. @icyblob  you can see the send form as reference because there you can also scan the public address for the destination of the transfer.

**Comment by sallymoc** [comment]
Please do not merge this until the qr scan missing button is addressed

**Comment by Qubic-Hub** [comment]
@icyblob can you please fix the conflicts so that I can merge?

**Pull request merged**
